import { Product, Category, Review } from '@/types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets and technology',
    image: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg',
    subcategories: [
      { id: '1-1', name: 'Smartphones', slug: 'smartphones', categoryId: '1' },
      { id: '1-2', name: 'Laptops', slug: 'laptops', categoryId: '1' },
      { id: '1-3', name: 'Headphones', slug: 'headphones', categoryId: '1' },
    ]
  },
  {
    id: '2',
    name: 'Fashion',
    slug: 'fashion',
    description: 'Trendy clothing and accessories',
    image: 'https://images.pexels.com/photos/934070/pexels-photo-934070.jpeg',
    subcategories: [
      { id: '2-1', name: 'Men\'s Clothing', slug: 'mens-clothing', categoryId: '2' },
      { id: '2-2', name: 'Women\'s Clothing', slug: 'womens-clothing', categoryId: '2' },
      { id: '2-3', name: 'Accessories', slug: 'accessories', categoryId: '2' },
    ]
  },
  {
    id: '3',
    name: 'Home & Garden',
    slug: 'home-garden',
    description: 'Everything for your home',
    image: 'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg',
    subcategories: [
      { id: '3-1', name: 'Furniture', slug: 'furniture', categoryId: '3' },
      { id: '3-2', name: 'Decor', slug: 'decor', categoryId: '3' },
      { id: '3-3', name: 'Garden', slug: 'garden', categoryId: '3' },
    ]
  },
];

export const products: Product[] = [
  // ELECTRONICS - HEADPHONES
  {
    id: '1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality wireless headphones with noise cancellation and premium sound quality. Perfect for music lovers and professionals.',
    price: 299.99,
    originalPrice: 399.99,
    images: [
      'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg',
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'AudioTech',
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    stockQuantity: 15,
    variants: [
      { id: '1-1', name: 'Color', value: 'Black', stockQuantity: 8 },
      { id: '1-2', name: 'Color', value: 'White', stockQuantity: 7 },
    ],
    tags: ['wireless', 'noise-cancelling', 'premium'],
    featured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    name: 'Gaming Headset Pro',
    description: 'Professional gaming headset with 7.1 surround sound, RGB lighting, and crystal-clear microphone for competitive gaming.',
    price: 149.99,
    originalPrice: 199.99,
    images: [
      'https://images.pexels.com/photos/3945667/pexels-photo-3945667.jpeg',
      'https://images.pexels.com/photos/4009402/pexels-photo-4009402.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Headphones',
    brand: 'GameSound',
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    stockQuantity: 28,
    variants: [
      { id: '2-1', name: 'Color', value: 'Black/Red', stockQuantity: 15 },
      { id: '2-2', name: 'Color', value: 'Black/Blue', stockQuantity: 13 },
    ],
    tags: ['gaming', 'rgb', 'microphone'],
    featured: false,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-18'),
  },

  // ELECTRONICS - SMARTPHONES
  {
    id: '3',
    name: 'ProMax Smartphone 256GB',
    description: 'Latest flagship smartphone with advanced camera system, 5G connectivity, and all-day battery life.',
    price: 899.99,
    images: [
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg',
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'TechPro',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    stockQuantity: 22,
    variants: [
      { id: '3-1', name: 'Color', value: 'Space Gray', stockQuantity: 8 },
      { id: '3-2', name: 'Color', value: 'Silver', stockQuantity: 7 },
      { id: '3-3', name: 'Color', value: 'Gold', stockQuantity: 7 },
    ],
    tags: ['5g', 'flagship', 'camera'],
    featured: true,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '4',
    name: 'Budget Smart Phone',
    description: 'Affordable smartphone with essential features, dual camera, and reliable performance for everyday use.',
    price: 199.99,
    images: [
      'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg',
      'https://images.pexels.com/photos/1616403/pexels-photo-1616403.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'ValueTech',
    rating: 4.2,
    reviewCount: 78,
    inStock: true,
    stockQuantity: 35,
    variants: [
      { id: '4-1', name: 'Color', value: 'Black', stockQuantity: 18 },
      { id: '4-2', name: 'Color', value: 'Blue', stockQuantity: 17 },
    ],
    tags: ['budget', 'reliable', 'dual-camera'],
    featured: false,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-21'),
  },

  // ELECTRONICS - LAPTOPS
  {
    id: '5',
    name: 'UltraBook Pro 15"',
    description: 'High-performance laptop with Intel i7 processor, 16GB RAM, and 512GB SSD. Perfect for professionals and creators.',
    price: 1299.99,
    originalPrice: 1499.99,
    images: [
      'https://images.pexels.com/photos/18105/pexels-photo.jpg',
      'https://images.pexels.com/photos/812264/pexels-photo-812264.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'CompuTech',
    rating: 4.8,
    reviewCount: 92,
    inStock: true,
    stockQuantity: 18,
    variants: [
      { id: '5-1', name: 'Color', value: 'Silver', stockQuantity: 10 },
      { id: '5-2', name: 'Color', value: 'Space Gray', stockQuantity: 8 },
    ],
    tags: ['professional', 'high-performance', 'ssd'],
    featured: true,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    id: '6',
    name: 'Gaming Laptop RTX',
    description: 'Powerful gaming laptop with RTX graphics, 32GB RAM, and 144Hz display for ultimate gaming experience.',
    price: 1899.99,
    images: [
      'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg',
      'https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'GameForce',
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    stockQuantity: 12,
    variants: [
      { id: '6-1', name: 'Storage', value: '1TB SSD', stockQuantity: 7 },
      { id: '6-2', name: 'Storage', value: '2TB SSD', stockQuantity: 5 },
    ],
    tags: ['gaming', 'rtx', 'high-refresh'],
    featured: false,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-17'),
  },

  // FASHION - MEN'S CLOTHING
  {
    id: '7',
    name: 'Organic Cotton T-Shirt',
    description: 'Comfortable and sustainable organic cotton t-shirt. Soft fabric with a perfect fit for everyday wear.',
    price: 29.99,
    images: [
      'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg',
      'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    brand: 'EcoWear',
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    stockQuantity: 45,
    variants: [
      { id: '7-1', name: 'Size', value: 'S', stockQuantity: 8 },
      { id: '7-2', name: 'Size', value: 'M', stockQuantity: 15 },
      { id: '7-3', name: 'Size', value: 'L', stockQuantity: 12 },
      { id: '7-4', name: 'Size', value: 'XL', stockQuantity: 10 },
    ],
    tags: ['organic', 'cotton', 'sustainable'],
    featured: false,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '8',
    name: 'Classic Denim Jeans',
    description: 'Premium quality denim jeans with classic fit and durable construction. Perfect for casual and smart-casual looks.',
    price: 79.99,
    originalPrice: 99.99,
    images: [
      'https://images.pexels.com/photos/1598507/pexels-photo-1598507.jpeg',
      'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Men\'s Clothing',
    brand: 'DenimCraft',
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    stockQuantity: 32,
    variants: [
      { id: '8-1', name: 'Size', value: '30', stockQuantity: 6 },
      { id: '8-2', name: 'Size', value: '32', stockQuantity: 10 },
      { id: '8-3', name: 'Size', value: '34', stockQuantity: 8 },
      { id: '8-4', name: 'Size', value: '36', stockQuantity: 8 },
    ],
    tags: ['denim', 'classic', 'durable'],
    featured: false,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-15'),
  },

  // FASHION - WOMEN'S CLOTHING
  {
    id: '9',
    name: 'Elegant Summer Dress',
    description: 'Beautiful floral summer dress made from breathable fabric. Perfect for casual outings and special occasions.',
    price: 89.99,
    images: [
      'https://images.pexels.com/photos/1536619/pexels-photo-1536619.jpeg',
      'https://images.pexels.com/photos/1462637/pexels-photo-1462637.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Women\'s Clothing',
    brand: 'FloralFashion',
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    stockQuantity: 24,
    variants: [
      { id: '9-1', name: 'Size', value: 'XS', stockQuantity: 4 },
      { id: '9-2', name: 'Size', value: 'S', stockQuantity: 6 },
      { id: '9-3', name: 'Size', value: 'M', stockQuantity: 8 },
      { id: '9-4', name: 'Size', value: 'L', stockQuantity: 6 },
    ],
    tags: ['floral', 'summer', 'elegant'],
    featured: true,
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    id: '10',
    name: 'Professional Blazer',
    description: 'Sophisticated blazer perfect for business meetings and professional settings. Tailored fit with premium materials.',
    price: 149.99,
    images: [
      'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg',
      'https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Women\'s Clothing',
    brand: 'ProStyle',
    rating: 4.8,
    reviewCount: 56,
    inStock: true,
    stockQuantity: 19,
    variants: [
      { id: '10-1', name: 'Size', value: 'S', stockQuantity: 5 },
      { id: '10-2', name: 'Size', value: 'M', stockQuantity: 7 },
      { id: '10-3', name: 'Size', value: 'L', stockQuantity: 7 },
    ],
    tags: ['professional', 'blazer', 'tailored'],
    featured: false,
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-20'),
  },

  // FASHION - ACCESSORIES
  {
    id: '11',
    name: 'Leather Crossbody Bag',
    description: 'Stylish genuine leather crossbody bag with multiple compartments. Perfect for daily use and travel.',
    price: 119.99,
    originalPrice: 149.99,
    images: [
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg',
      'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'LeatherLux',
    rating: 4.5,
    reviewCount: 73,
    inStock: true,
    stockQuantity: 16,
    variants: [
      { id: '11-1', name: 'Color', value: 'Brown', stockQuantity: 8 },
      { id: '11-2', name: 'Color', value: 'Black', stockQuantity: 8 },
    ],
    tags: ['leather', 'crossbody', 'travel'],
    featured: false,
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    id: '12',
    name: 'Classic Wrist Watch',
    description: 'Timeless analog watch with stainless steel case and leather strap. Water-resistant and elegant design.',
    price: 199.99,
    images: [
      'https://images.pexels.com/photos/190819/pexels-photo-190819.jpeg',
      'https://images.pexels.com/photos/277390/pexels-photo-277390.jpeg',
    ],
    category: 'Fashion',
    subcategory: 'Accessories',
    brand: 'TimeClassic',
    rating: 4.6,
    reviewCount: 91,
    inStock: true,
    stockQuantity: 21,
    variants: [
      { id: '12-1', name: 'Strap', value: 'Brown Leather', stockQuantity: 11 },
      { id: '12-2', name: 'Strap', value: 'Black Leather', stockQuantity: 10 },
    ],
    tags: ['watch', 'classic', 'water-resistant'],
    featured: false,
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-14'),
  },

  // HOME & GARDEN - FURNITURE
  {
    id: '13',
    name: 'Modern Dining Table',
    description: 'Contemporary dining table for 6 people. Made from solid oak wood with a sleek finish.',
    price: 599.99,
    originalPrice: 799.99,
    images: [
      'https://images.pexels.com/photos/1350789/pexels-photo-1350789.jpeg',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Furniture',
    brand: 'WoodCraft',
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    stockQuantity: 8,
    variants: [
      { id: '13-1', name: 'Finish', value: 'Natural Oak', stockQuantity: 4 },
      { id: '13-2', name: 'Finish', value: 'Dark Walnut', stockQuantity: 4 },
    ],
    tags: ['dining', 'oak', 'modern'],
    featured: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    id: '14',
    name: 'Comfortable Office Chair',
    description: 'Ergonomic office chair with lumbar support, adjustable height, and breathable mesh back.',
    price: 249.99,
    images: [
      'https://images.pexels.com/photos/2181996/pexels-photo-2181996.jpeg',
      'https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Furniture',
    brand: 'ErgoComfort',
    rating: 4.5,
    reviewCount: 67,
    inStock: true,
    stockQuantity: 15,
    variants: [
      { id: '14-1', name: 'Color', value: 'Black', stockQuantity: 8 },
      { id: '14-2', name: 'Color', value: 'Gray', stockQuantity: 7 },
    ],
    tags: ['ergonomic', 'office', 'adjustable'],
    featured: false,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-19'),
  },

  // HOME & GARDEN - DECOR
  {
    id: '15',
    name: 'Modern Floor Lamp',
    description: 'Sleek and modern floor lamp with adjustable brightness. Perfect for reading nooks and living spaces.',
    price: 149.99,
    images: [
      'https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg',
      'https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Decor',
    brand: 'IllumiHome',
    rating: 4.7,
    reviewCount: 43,
    inStock: true,
    stockQuantity: 12,
    tags: ['modern', 'lighting', 'adjustable'],
    featured: false,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '16',
    name: 'Abstract Wall Art Set',
    description: 'Set of 3 abstract canvas prints to enhance your living space. Modern design with vibrant colors.',
    price: 89.99,
    originalPrice: 119.99,
    images: [
      'https://images.pexels.com/photos/1579708/pexels-photo-1579708.jpeg',
      'https://images.pexels.com/photos/1579739/pexels-photo-1579739.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Decor',
    brand: 'ArtVibe',
    rating: 4.4,
    reviewCount: 38,
    inStock: true,
    stockQuantity: 25,
    variants: [
      { id: '16-1', name: 'Size', value: '12x16 inches', stockQuantity: 13 },
      { id: '16-2', name: 'Size', value: '16x20 inches', stockQuantity: 12 },
    ],
    tags: ['abstract', 'wall-art', 'canvas'],
    featured: false,
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-13'),
  },

  // HOME & GARDEN - GARDEN
  {
    id: '17',
    name: 'Ceramic Plant Pots Set',
    description: 'Set of 4 beautiful ceramic plant pots with drainage holes. Perfect for indoor plants and herbs.',
    price: 49.99,
    images: [
      'https://images.pexels.com/photos/1005058/pexels-photo-1005058.jpeg',
      'https://images.pexels.com/photos/1084199/pexels-photo-1084199.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Garden',
    brand: 'GreenThumb',
    rating: 4.6,
    reviewCount: 52,
    inStock: true,
    stockQuantity: 30,
    variants: [
      { id: '17-1', name: 'Color', value: 'White', stockQuantity: 15 },
      { id: '17-2', name: 'Color', value: 'Terracotta', stockQuantity: 15 },
    ],
    tags: ['ceramic', 'plants', 'drainage'],
    featured: false,
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-11'),
  },
  {
    id: '18',
    name: 'Garden Tool Set',
    description: 'Complete 5-piece garden tool set with ergonomic handles. Includes trowel, pruner, weeder, and more.',
    price: 79.99,
    originalPrice: 99.99,
    images: [
      'https://images.pexels.com/photos/4505166/pexels-photo-4505166.jpeg',
      'https://images.pexels.com/photos/4505168/pexels-photo-4505168.jpeg',
    ],
    category: 'Home & Garden',
    subcategory: 'Garden',
    brand: 'GardenPro',
    rating: 4.8,
    reviewCount: 76,
    inStock: true,
    stockQuantity: 18,
    variants: [
      { id: '18-1', name: 'Handle', value: 'Wood', stockQuantity: 9 },
      { id: '18-2', name: 'Handle', value: 'Rubber Grip', stockQuantity: 9 },
    ],
    tags: ['tools', 'ergonomic', 'complete-set'],
    featured: false,
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-10'),
  },

  // ADDITIONAL FEATURED PRODUCT
  {
    id: '19',
    name: 'Smart Fitness Watch',
    description: 'Advanced fitness tracking with heart rate monitoring, GPS, and smart notifications. Water-resistant design for active lifestyles.',
    price: 249.99,
    images: [
      'https://images.pexels.com/photos/393047/pexels-photo-393047.jpeg',
      'https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg',
    ],
    category: 'Electronics',
    subcategory: 'Wearables',
    brand: 'FitTech',
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    stockQuantity: 23,
    variants: [
      { id: '19-1', name: 'Size', value: '42mm', stockQuantity: 12 },
      { id: '19-2', name: 'Size', value: '46mm', stockQuantity: 11 },
    ],
    tags: ['fitness', 'smartwatch', 'health'],
    featured: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    productId: '1',
    userId: '1',
    userName: 'Sarah Johnson',
    userAvatar: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
    rating: 5,
    title: 'Amazing sound quality!',
    comment: 'These headphones exceeded my expectations. The noise cancellation is fantastic and the sound quality is crystal clear.',
    verified: true,
    createdAt: new Date('2024-01-22'),
  },
  {
    id: '2',
    productId: '1',
    userId: '2',
    userName: 'Mike Chen',
    rating: 4,
    title: 'Great value for money',
    comment: 'Solid headphones with good battery life. The only minor issue is they can feel a bit tight after long sessions.',
    verified: true,
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '3',
    productId: '3',
    userId: '3',
    userName: 'Emily Davis',
    rating: 5,
    title: 'Best smartphone I\'ve owned',
    comment: 'The camera quality is incredible and the battery lasts all day. Highly recommend!',
    verified: true,
    createdAt: new Date('2024-01-21'),
  },
  {
    id: '4',
    productId: '5',
    userId: '4',
    userName: 'David Wilson',
    rating: 5,
    title: 'Perfect for work',
    comment: 'Fast, reliable, and great build quality. Perfect laptop for professional use.',
    verified: true,
    createdAt: new Date('2024-01-19'),
  },
  {
    id: '5',
    productId: '9',
    userId: '5',
    userName: 'Lisa Anderson',
    rating: 4,
    title: 'Beautiful dress',
    comment: 'Love the floral pattern and the fabric is very comfortable. Fits perfectly!',
    verified: true,
    createdAt: new Date('2024-01-17'),
  },
];